### ISSUE TITLE
Literal is broken

### ISSUE THREAD

**Issue by apirogov** [bojiang/typing_utils#14]
After the recent pull request, issubtype produces incorrect results for Literals and exceptions when string literals are used.

EDIT: apparently the incorrect behavior was there already before, but now instead of RecursionError there is another error

**Comment by bojiang** [comment]
Could you open a PR to the unit tests with the bad case?

**Comment by apirogov** [comment]
```python
from typing_utils import issubtype
from typing_extensions import Literal
```

With PyPI Version (0.1.0):

* `issubtype(Literal[1], Literal[1,2])` is `False` (should be `True`) <- so this problem already was there before
* `issubtype(Literal[1,2], Literal[2,1])` is `False` (should be `True`) <-
* `issubtype(Literal["a"], Literal["a", "b"])` triggers `RecursionError` (should be `True`)

With current commit ([2e47505](https://github.com/bojiang/typing_utils/commit/2e475058f3bd5bb84b393f49b1204c7084312acc)) what changed is:

* `issubtype(Literal["a"], Literal["a", "b"])` now produces

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/admin/.pyenv/versions/3.8.10/lib/python3.8/site-packages/typing_utils/__init__.py", line 430, in issubtype
    return _is_normal_subtype(normalize(left), normalize(right), forward_refs)
  File "/home/admin/.pyenv/versions/3.8.10/lib/python3.8/site-packages/typing_utils/__init__.py", line 395, in _is_normal_subtype
    return _is_origin_subtype_args(left.args, right.args, forward_refs)
  File "/home/admin/.pyenv/versions/3.8.10/lib/python3.8/site-packages/typing_utils/__init__.py", line 315, in _is_origin_subtype_args
    and left[-1].origin is not Ellipsis
AttributeError: 'str' object has no attribute 'origin'
```

Furthermore I don't see any unit tests in place for `Literal` at all...

**Comment by KholdStare** [comment]
Any updates on this?

**Comment by apirogov** [comment]
I personally migrated to [runtype](https://github.com/erezsh/runtype)

**Comment by KholdStare** [comment]
@apirogov Thanks! That's great!
